language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
rvm:
  - ruby-head
  - jruby-head
  - jruby-19mode
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
    - TEST=true
script: bundle exec rake test
